name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Build-Project-Linux:
    name: Build Project on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure and Build Project
        run: |
          cmake -H. -B_build
          cmake --build _build
      - name: Run tests
        run: _build/check

  Build-Project-Windows:
    name: Build Project on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Configure and Build Project
        run: |
          mkdir _build
          cd _build
          cmake ..
          cmake --build .
      - name: Run tests
        run: _build\Debug\check.exe
